cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: us-west-2
    stack:
      auto: false

application:
  bucket:
    name: camille-test-bucket
